### PR TITLE
[Spanish Phonemizer] More consonant tweaks + new functions

### PR DESCRIPTION
**Pull request by lottev1991**
**TODO:** Add VV fallback function for lacking semivowel clusters.

### CODE REVIEW

**Comment by juanjosse** [comment]
How is it supposed to be used? The voice (Violet Aura) does not sound :S

**Comment by lottev1991** [comment]
I'm sorry, but this is just a merge request, not a help forum.

**Comment by juanjosse** [comment]
Where can I ask to you? I have downloaded your Hoshino Hanami and it sounds very well in Spanish. But I don't know how to install the Presamp or AutoCVVC, please tell me how I can contact you.
I am also a programmer so I could help in new features, like building a plugin to integrate OpenUTAU in DAWs.
Thank you.

**Comment by lottev1991** [comment]
Please stop replying to this pull request.

**Pull request merged**
