### PR TITLE
Add KoreanPhonemizerUtil

### PR DESCRIPTION
**Pull request by EX3exp**
- Added KoreanPhonemizerUtil.cs, and This class will be used in **Diffsinger Korean Phonemizer**, **other Multiple Korean Phonemizers(including Classic)**.
- Implementing Korean Phoneme Variation(like 꽃망울에 to [꼰망우레]), Jamo separation(like 간 to ㄱㅏㄴ), Jamo merge(like ㄱㅏㄴ to 간) in Each phonemizers makes Korean Plugin developers struggle.... So I made KoreanPhonemizerUtil, to increase Productivity and Code re-using.
- Also supports .ini management, currently used by KO CV Phonemizer & KO ENUNU Phonemizer.

- If this branch merged, I want to PR two Classic Korean Phonemizers and Diffsinger Korean Phonemizer which using this class. 👀 (+ [23.12.28] Korean ENUNU Phonemizer uses this class too)

### CODE REVIEW

**Comment by oxygen-dioxide** [comment]
Why do you add a new ini parser implementation instead of using the existing code in openutau https://github.com/stakira/OpenUtau/blob/master/OpenUtau.Core/Classic/Ini.cs ?

**Comment by oxygen-dioxide** [comment]
Also if you're adding custom dictionary support, yaml is a better format because it is more extensible, and most other phonemizers use yaml.

**Comment by EX3exp** [comment]
> Why do you add a new ini parser implementation instead of using the existing code in openutau https://github.com/stakira/OpenUtau/blob/master/OpenUtau.Core/Classic/Ini.cs ?

Oh... It was my mistake...😲 I'll fix ini parsing implementation right away. Thanks for mentioning it!

**Comment by EX3exp** [comment]
> Also if you're adding custom dictionary support, yaml is a better format because it is more extensible, and most other phonemizers use yaml.

I either think .yaml format would be better choice... I'll change dictionary's format into yaml. Thanks for your advice!

**Comment by EX3exp** [comment]
I Fixed BaseIniManager's implementation to use OpenUtau's `Ini.cs`, and now KO ENUNU Phonemizer uses user-customed Jamo dictionary in Yaml format(`jamo_dict.yaml`). 👀

**Pull request merged**
