### PR TITLE
Add MusicXML Import

### PR DESCRIPTION
**Pull request by porime42**
Adding MusicXML capabilities may be the starting point for future support with NEUTRINO. This PR is for importing.

[XmlSchemaClassGenerator](https://github.com/mganss/XmlSchemaClassGenerator) used to generate [MusicXML 4.0](https://www.musicxml.com/for-developers/musicxml-xsd/) schema for use with `XmlSerializer`. Most of new lines of code comes from it in: `MusicXMLSchema.cs`

Corresponding [Discord Thread](https://discord.com/channels/551606189386104834/1223625244514713731)

### CODE REVIEW

**Comment by porime42** [comment]
image
image
Able to use filepicker to open musicxml files and read lyrics atm

**Comment by porime42** [comment]
image
Pitch, Tone, and Duration fields being read. 

Thinking now about how key signatures, time signatures, and whole/half/eighth/sixteenth/etc. notes interpreted.

**Comment by porime42** [comment]
Each individual notes includes information under the `<alter>` tag when exported:
https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/alter/

Verified under MuseScore. Keeping track of key signatures is unneeded.

Also for reference: https://www.musicxml.com/publications/makemusic-recordare/notation-and-analysis/a-sample-musicxml-encoding/

**Comment by porime42** [comment]
There exists compressed musicxml following the zip compression method but that can be addressed seperately.

**Comment by porime42** [comment]
Remember to check for character encoding, can see https://github.com/stakira/OpenUtau/blob/b969d52860bf03502418b0f9353723c9f61d0450/OpenUtau.Core/Format/Midi.cs#L32 for an example.

Check the entire `.musicxml` file to determine character encoding. It is assumed if the lyrics are in a different character encoding, so shall the `.musicxml` and vice-versa.

**Comment by porime42** [comment]
Regarding length of time, the `<divisions>` and `<duration>` are linked to one another: https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/divisions/

Seems to be a viable way of interpreting note length. Apaper published on 2021 provides details on the `<duration>` element and a survey on how it is used in various programs: https://musescore.org/sites/musescore.org/files/2021-05/TN-MXML-duration-overview-i01.pdf

The `<type>` element may be an alternative usable with the single dot `<dot>` element and double dot `<double-tongue>` element. Purpose appears to be for graphical representation however. https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/type/

**Comment by digits58** [comment]
Using a sample MusicXML provided by NEUTRINO, importing into OpenUTAU, and rendering with Teto appears to match the result of the render from NEUTRINO with Zundamon

**Comment by porime42** [comment]
Importing MusicXML is implemented.

Using a sample MusicXML provided by NEUTRINO, importing into OpenUTAU, and rendering with Teto appears to match the result of the render from NEUTRINO with Zundamon

**Comment by porime42** [comment]
image
Export menu item added and functionality working

**Comment by porime42** [comment]
Valid skeleton MusicXML being exported
image

Now to figure out exporting notes.

**Comment by porime42** [comment]
Export compatibility is primarily for NEUTRINO. MusicXML is actually only used as an intermediary format to be converted to HTS `.lab`  with a bundled utility named musicXMLtoLabel according to the the script which runs NETURINO:
image

The utility appears to be derived from https://github.com/taroushirani/xml2lab works which itself seems to draw from https://www.sinsy.jp/

Food for thought, perhaps it's possible to skip straight to the `.lab` format.

**Comment by porime42** [comment]
Able to have no elements under for full rest `<measure number="1"/>`. Measures don't appear skip-able in number however

**Comment by porime42** [comment]
Order that elements occur in a measure matter

note, note, time signature, note != time signature, note, note, note

**Comment by porime42** [comment]
There might be some incompatibility between programs. OpenUTAU and pals allows tempo and time signature change basically anywhere. MuseScore doesn't seem to allow it and following from that I dunno whether this is acceptable in the MusicXML standard.

**Comment by porime42** [comment]
For sake of simplicity, leaving out support for tempo and time signature changes in the middle of a measure.

Future changes add it can probably rewrite/customization serialization behaviour to do stuff like target NEUTRINO

**Comment by porime42** [comment]
Use `GetMinDurTick` or related to get minimum length. Can use that with BPM and time signature number to calculate the total number of measures to export.

Use dynamic programming to efficiently translate OpenUtau notes to MusicXML notes. See coin change and/or knapsack problem for reference. Data structures and algorithms coming in handy :thinking:

**Comment by porime42** [comment]
Splitting Import/Export into different PR's to reduce complexity and have Import for testing earlier. Export will be handled in another PR

**Comment by stakira** [comment]
Could you add some unit tests for this importer?

**Comment by oxygen-dioxide** [comment]
I added some unit tests for this musicxml importer.

https://github.com/oxygen-dioxide/OpenUtau/commit/23b9183adefebb62508512cf478daf7819f00a0b

Musicxml files come from [cuthbertLab/musicxmlTestSuite](https://github.com/cuthbertLab/musicxmlTestSuite)

**Comment by porime42** [comment]
Thank you!

**Pull request merged**
