### PR TITLE
Add Millefeuille French and Marzipan German Phonemizers

### PR DESCRIPTION
**Pull request by imsupposedto**
French is UFR Millefeuille and Marzipan German is a new system. For Marzipan it has a new phoneme system, hand written dict, and improved G2P performance over existing German phonemizer. All Millefeuille vbs will update with this phoneme system in the future as native integration and XLS for Marzipan within Millefeuille is currently being tested. Phonetic system created and owned by imsupposedto.

### CODE REVIEW

**Comment by stakira** [comment]
Please try to avoid flipping line endings in files. You can see Github shows diff for every line of `LyricsHelper.cs` and `PhoneticAssistantViewModel.cs` just because the line ending change. If you use VS or VS Code, at the right bottom corner where shows CRLF or LF you should be able to change the line ending for file.

**Comment by imsupposedto** [comment]
> Please try to avoid flipping line endings in files. You can see Github shows diff for every line of `LyricsHelper.cs` and `PhoneticAssistantViewModel.cs` just because the line ending change. If you use VS or VS Code, at the right bottom corner where shows CRLF or LF you should be able to change the line ending for file.

What line ending type does it need to be?

**Comment by lottev1991** [comment]
@imsupposedto It should be CRLF.

**Comment by imsupposedto** [comment]
> @imsupposedto It should be CRLF.

Hm, I hadn't changed it from that. Must be some weird Visual Studio thing. I'm correcting it now and will update the pull request

**Pull request closed without merging**
