### PR TITLE
[Classic KO Phonemizer] Add CV, Update CBNN / [DiffSinger] Feat: automatically downloads vocoder from git / [Diffsinger Phonemizer] Add KO Phonemizer / Fix losing focus at new pianoroll window  / Enhanced UI 

### PR DESCRIPTION
**Pull request by EX3exp**
- Added Korean CV Phonemizer.
- Added Diffsinger Korean Phonemizer. 
- Updated Korean CBNN Phonemizer.
- Implemented "Korean phoneme variation" in above phonemizers.
 
- KO DIFFS Phonemizer automatically handles semivowel(= y, w)'s timing, so no loosy pronunciation.

- If user has no nsf_hifigan vocoder and cannot playback Diffsinger's song voice, OpenUtau automatically downloads nsf_hifigan from xunmenshe's archive and completes installation.
So, user can immediately listen Diffsinger's song voice, instead of go to the archive link, download oudep, and put that into "Install Singer" menu. It makes better user experience.  
- Fixed losing focus from lyric edit box to horizontal scrollbar, when new piano roll window created.
- Enhanced UI: Better readablilty

### CODE REVIEW

**Comment by stakira** [comment]
Could you see if you can simplify the code with arrays and loops? Code this long will be difficult to read and maintain.

**Comment by EX3exp** [comment]
> Could you see if you can simplify the code with arrays and loops? Code this long will be difficult to read and maintain.

I've tried but couldn't replace all if statements into loops, instead I improved readability through functions and modularization. 
It has been better than before, in terms of understanding and maintaining codes. 👀

**Comment by EX3exp** [comment]
I added a feature in DiffSingerVocoder.cs : 
- For enhanced User Experience, It downloads `nsf-hifigan.oudep` Directly from [xunmengshe's Vocoder Archive](https://github.com/xunmengshe/OpenUtau/wiki/Vocoders) in Cache Folder.(downloading process is async)
- After Downloading, it Installs `nsf-hifigan.oudep` using DependencyInstaller. 
- After installing vocoder, it automatically tries to delete  `nsf-hifigan.oudep`.

**Comment by EX3exp** [comment]
- Fixed losing focus when trying to edit lyric at New piano roll window. (in that case, focus was lost FROM lyric edit box TO H-scrollbar.)
- Enhanced UI. 
  - Changed some Icons to new vector.
  - Enhanced readability, by changing some padding & margin & 1px bigger font size.
  
image
image
image
image

**Comment by EX3exp** [comment]
Simplified some codes... I really finished.

**Comment by stakira** [comment]
Please keep PRs focused and self-contained. It's difficult to review large combined PRs.

**Comment by oxygen-dioxide** [comment]
Some suggestions about the oudep downloader:
- Not all the diffsinger voicebanks use nsf_hifigan vocoder.
- The current implementation catchs all the errors when loading the vocoder. Maybe the vocoder is already downloaded but OpenUtau fails to load it for some other reason, or the user is developing their own vocoder. I should write a better detection code for this. 
- The vocoder will be downloaded without asking the user. Even if the user is using a metered connection, the file will be downloaded. If the user have auto rendering enabled, the vocoder will be downloaded once the user opens the file. OpenUtau should ask the user before downloading.
I think we should have a "download center" in OpenUtau for all the oudep dependencies, like that in UVR and SynthV

**Comment by EX3exp** [comment]
> Please keep PRs focused and self-contained. It's difficult to review large combined PRs.

I'm sorry about this. I'll separate PRs right now so they stay self-contained.
I think this may sound very weird, I either thought this PR is so messy but I recently knew how to separate PRs because I was github begginner...🫠  Mistakes like this will not happen next time, I'll try my best.

**Comment by EX3exp** [comment]
> Some suggestions about the oudep downloader:
> 
> * Not all the diffsinger voicebanks use nsf_hifigan vocoder.
> * The current implementation catchs all the errors when loading the vocoder. Maybe the vocoder is already downloaded but OpenUtau fails to load it for some other reason, or the user is developing their own vocoder. I should write a better detection code for this.
> * The vocoder will be downloaded without asking the user. Even if the user is using a metered connection, the file will be downloaded. If the user have auto rendering enabled, the vocoder will be downloaded once the user opens the file. OpenUtau should ask the user before downloading.
>   I think we should have a "download center" in OpenUtau for all the oudep dependencies, like that in UVR and SynthV



> Some suggestions about the oudep downloader:
> 
> * Not all the diffsinger voicebanks use nsf_hifigan vocoder.
> * The current implementation catchs all the errors when loading the vocoder. Maybe the vocoder is already downloaded but OpenUtau fails to load it for some other reason, or the user is developing their own vocoder. I should write a better detection code for this.
> * The vocoder will be downloaded without asking the user. Even if the user is using a metered connection, the file will be downloaded. If the user have auto rendering enabled, the vocoder will be downloaded once the user opens the file. OpenUtau should ask the user before downloading.
>   I think we should have a "download center" in OpenUtau for all the oudep dependencies, like that in UVR and SynthV

Thanks for suggestions, I think Making "download center" is a good idea.

Then I'll try:🔽
- Instead of downloading vocoder without asking user, make OU to open "download center" automatically, so user can select and download dependencies with ease.
- Try implementing "download center" with below(🔽) suggestions.
- Try to modify error handling part, so can cover various cases.


And these are my suggestions about "download center".🔽

1. `download center` will should have these features:
   - Can show "all available dependencies' list" to user.
   - Can show status of "which dependencies are installed (or not)", like (nsf_hifigan  Uninstalled   [info]  [download]).
  **Download buttons of "already installed dependency" should be blocked, so user cannot reach them.**
   - When user clicks specific dependency's download button, It should confirm to user by message window, like "Will you download dependency (XXX)?(total: XXMb)".
   - Can show downloaded status, like (50% -- 50Mb/ 100Mb). (showing progress bar will be great for user experience)
   - Can perform more than one download at once, in async process.

   - Can categorize dependencies, like "Diffsinger / Vogen / ENUNU... etc." (good to use combobox)

2. I think It will be great to use `download center.yaml` to manage "download center".
    - So exactly what "download center" perform is : 
      - print dependencies' informations in `download center.yaml` into user view
      - connect download link(in `download center.yaml`) with each dependency's download button.

3) And  `download center.yaml` should contain: 
   - oudep's name (like "nsf_hifigan")
   - oudep's category (like "diffsinger)
   - oudep's brief information (like "use when rendering diffsinger's voice...blahblah")
   - oudep's file size(Mb)
   - oudep's direct download link (github, google drive... anything.)

**Pull request closed without merging**
