### PR TITLE
Pitch Baking

### PR DESCRIPTION
**Pull request by oxygen-dioxide**
An editing macro that converts PITD to pitch points is added.

### CODE REVIEW

**Comment by oxygen-dioxide** [comment]
Current state: pitch point reducing strategy is adopted from https://github.com/oatsu-gh/ENUNU/blob/main/synthesis/extensions/f0_feedbacker.py . Only extreme points are preserved, which will lose many features when the pitchline is going up or down, but keep too much points when the pitchline is nearly horizontal. 

Todo:
- improve the pitch point reducing strategy. (feel free to share your idea here)
- improve the pitch point distribution strategy. 
- Unit test

**Comment by oxygen-dioxide** [comment]
Now Ramer–Douglas–Peucker algorithm is used to reduce points like how [utaformatix](https://github.com/sdercolin/utaformatix3) does. Pitchlines are splited at the position with the minimal delta to the tone of the note, which will enhance user experience, because the rapid change of pitch between notes won't be splited into two notes.

image
(The pitch here is generated by nnsvs)

**Comment by oxygen-dioxide** [comment]
There is still an issue: the user have to press ctrl-Z twice to fully redo this action. One for applying the pitchpoints and one for erasing PITD.

**Comment by stakira** [comment]
> There is still an issue: the user have to press ctrl-Z twice to fully redo this action. One for applying the pitchpoints and one for erasing PITD.

Seems an easy fix?

**Pull request merged**
